version: "3.7"
services:
  app:
    build:
      args:
        user: fab
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: phpapi
    container_name: phpapi-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - web
      - mysql
    networks:
      - phpapi

  web:
    image: nginx:latest
    container_name: phpapi-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - phpapi

  mysql:
    image: mysql:5.7
    container_name: phpapi-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test"
      # MYSQL_USER: "user"
      # MYSQL_PASSWORD: "user"
    ports: 
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - phpapi

networks:
  phpapi:
    driver: bridge
